### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Kresqle** [ascpial/GameTest#1]
Bonsoir,
J’ai lu le README mais il n’existe aucune explication quant à l’installation de votre jeu.
Serait-il possible d’ajouter cette section ?
Merci

**Comment by ascpial** [comment]
Merci pour ton retour sur le jeu !

Ça sera fait dans les 30 minutes !

**Comment by Kresqle** [comment]
> Merci pour ton retour sur le jeu !
> 
> Ça sera fait dans les 30 minutes !

De rien, c’est normal 😉 

Super, merci ! :)

**Comment by ascpial** [comment]
J'ai ajouté la section installation tout en bas du README.md pour récompenser ce qui ont lu tout le fichier avec le commit 9f99fd0 !

**Comment by Kresqle** [comment]
> J'ai ajouté la section installation tout en bas du README.md pour récompenser ce qui ont lu tout le fichier avec le commit [9f99fd0](https://github.com/ascpial/GameTest/commit/9f99fd0179ec91f1e82ee205d6caad3454ee98b8) !

Merci sale bg
